version: '3.8'

services:
  putabotonit:
    image: "putabotonit"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - 9229:9229
    command: ["npm", "run", "dev"]
