app = "put-a-bot-on-it"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[build]
  builder = "heroku/buildpacks:20" # "paketobuildpacks/builder:full"
  buildpacks = ["heroku/nodejs"] # "gcr.io/paketo-buildpacks/nodejs"

  [build.args]
    NODE_ENV="production"

[env]
  NODE_ENV="production"

[mounts]
  source="put_a_disk_on_it"
  destination="/local-storage"

[experimental]
  allowed_public_ports = []
  cmd = []
  entrypoint = []
  exec = []
