app = "put-a-bot-on-it"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[env]
  NODE_ENV="production"

[mounts]
  source="put_a_disk_on_it"
  destination="/local-storage"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
