export const commands = [
  {
    name: 'Steve Harvey',
    value: `'steve harvey'`,
    emoji: ['steve'],
    allowQuery: true,
  },
  {
    name: 'ALF',
    value: 'alf',
    emoji: ['alf'],
    allowQuery: true,
  },
  {
    name: 'Borat',
    value: 'borat',
    emoji: ['borat', 'great_success'],
    allowQuery: true,
  },
  {
    name: 'Rick and Morty',
    value: `'rick and morty'`,
    emoji: ['rick', 'morty', 'portal'],
    allowQuery: true,
  },
  {
    name: 'Seinfeld',
    value: 'seinfeld',
    emoji: ['kramer'],
    allowQuery: true,
  },
  {
    name: 'South Park',
    value: `'south park'`,
    emoji: ['towelie'],
    allowQuery: true,
  },
  {
    name: 'Star Wars',
    value: `'star wars'`,
    emoji: ['darth_vader', 'yoda'],
    allowQuery: true,
  },
  {
    name: 'Snoop Dogg',
    value: `'snoop dogg'`,
    emoji: ['snoop'],
    allowQuery: true,
  },
  {
    name: 'Wu-Tang Clan',
    value: `'wu-tang clan'`,
    emoji: ['wutang'],
    allowQuery: true,
  },
  {
    name: "Tourette's Guy",
    value: `'tourettes guy'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: 'Trebek (SNL Celebrity Jeopardy)',
    value: `'snl celebrity jeopardy'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: 'Uncle Roger',
    value: `'uncle roger'`,
    emoji: ['uncle_roger'],
    allowQuery: true,
  },
  {
    name: 'Steven He',
    value: `'steven he'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: 'Putin',
    value: 'putin',
    emoji: ['putin'],
    allowQuery: true,
  },
  {
    name: 'Muppets',
    value: 'muppets',
    emoji: ['swedish_chef'],
    allowQuery: true,
  },
  {
    name: `Chapelle's Show`,
    value: `'chapelle show'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: `Star Trek`,
    value: `'star trek'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: `RTJ`,
    value: `'run the jewels'`,
    emoji: null,
    allowQuery: true,
  },
  {
    name: `Game of Thrones`,
    value: `'game of thrones'`,
    emoji: null,
    allowQuery: true,
  },
];
